# Generated by Django 3.2.13 on 2022-08-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wishlist', 'saqlash'), ('blacklist', 'qora ro`yxat')], max_length=50, verbose_name='Tip')),
                ('author_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('author_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_binds', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_binds', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'model bind',
                'verbose_name_plural': 'model binds',
                'unique_together': {('author_content_type', 'author_object_id', 'target_content_type', 'target_object_id', 'type')},
            },
        ),
    ]
