# Generated by Django 3.2.13 on 2022-08-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_wishlist_blacklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('author_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blacklists', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_blacklists', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'blacklist',
                'verbose_name_plural': 'blacklists',
                'unique_together': {('author_content_type', 'author_object_id', 'target_content_type', 'target_object_id')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('author_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_wishlists', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_wishlists', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlists',
                'unique_together': {('author_content_type', 'author_object_id', 'target_content_type', 'target_object_id')},
            },
        ),
        migrations.DeleteModel(
            name='ModelBind',
        ),
    ]
